[package]
name = "sebastian2852/encapsulate-react"
description = "Simple state managment"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"
authors = [ "sebastian2852" ]
realm = "shared"
exclude = ["**", "**/*", "**/**"]
include = [ "source", "source/**/*", "wally.toml", "LICENSE", "default.project.json" ]

[dependencies]
React = "jsdotlua/react@^17"
encapsulate = "sebastian2852/encapsulate@^0.1"