[package]
name = "sebastian2852/encapsulate"
registry = "https://github.com/UpliftGames/wally-index"
version = "0.0.1"
realm = "shared"
private = true

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
React = "jsdotlua/react@^17"